### ISSUE TITLE
Missing disciple?

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#104]
It looks to me like Wikidata is ok for this disciple of Linnaeus: Andreas Berlin—he’s got loads of identifiers, but I’m not sure that they’re the ones you generally look for: https://www.wikidata.org/wiki/Q496118

I went looking for him several weeks ago and figured I'd give it a little time. Some of the others have, but he's still not popping up. Any thoughts or suggestions?

**Comment by dshorthouse** [comment]
The identifiers I watch for include one or more of IPNI, Harvard Index of Botanists, Entomologists of the World, ZooBank Author ID, or BHL Creator ID. Your disciple has none of those so is a good candidate for manual addition. I just now added him to Bloodhound.
