### ISSUE TITLE
Why are my records not found?

### ISSUE THREAD

**Issue by nielsraes** [dshorthouse/bloodhound#118]
I wondered why these records https://www.gbif.org/occurrence/search?recorded_by=raes%20n;%20risasmoko%20a;%20harley%20rm;%20slik%20jwf;%20hovenkamp%20ph&advanced=1 do not show up under my name Raes N

**Comment by dshorthouse** [comment]
Thanks, Niels. Good catch! This one was a shortcoming in the stand-alone ruby gem I made to parse content of recordedBy or identifiedBy. I've made adjustments (and a [test](https://github.com/dshorthouse/dwc_agent/commit/a95fd63b57263c6872760238ca1fc51f62fa0727#diff-b0ef76a1aab36c62d6f29b40f7936a5fR153)!) so these should appear the next time I do a harvest of GBIF data in a few weeks.
