### ISSUE TITLE
Add ability to ignore records in candidate list

### ISSUE THREAD

**Issue by dshorthouse** [dshorthouse/bloodhound#13]
As in subject heading.

**Comment by dshorthouse** [comment]
Yep, that's exactly what I meant. I too have family - mother & father whose specimens I'd rather not see. I know exactly what other things they were up to while collecting, especially nine months before I was born. Those are actions that ought never to have URIs.

**Comment by deepreef** [comment]
Ha!!  That’s awesome!  I also forgot to mention that “L. Pyle”, who shows up on a few records, is my mom – though I haven’t found any records collected by my parents nine months before my birth….

**Comment by dshorthouse** [comment]
Committed and deployed. Added a "Hide" button for each specimen in the candidate list.

**Comment by deepreef** [comment]
Nice!  So... what is your approach to tracking this?  There are several areas in my data world where I would like to record an explicit "not" statement about a relationship between two records (e.g., This John Smith was NOT the collector of that specimen; This dirty record for an agent/reference/journal/taxon/whatever is NOT linked to this clean record; This taxon was NOT observed at this locality during this event; etc.)  There are a few different ways to model this sort of thing, either using the existing structure for managing 1:M relationships with some sort of flag field or type value; or a dedicated structure to explicitly deal with "not" conditions.  Just curious how you are handling it here.

**Comment by dshorthouse** [comment]
I stuck with the most basic way I could do this in the context at hand - a boolean column entitled "visible" in a join table between users and occurrences. And so the adjacent "action" details column remains NULL when visible = 0 in this same table. If I were to also permit users to add a note (or more flexibility in what it was they were annotating) then I'd most certainly need to refactor this. That said, the typical object-relational logic is now a bit peculiar in my code because the "show me all user x's occurrences and actions" method is now emended with a new method that includes "EXCEPT those records she's flagged as 'not her' dammit".
