### ISSUE TITLE
Show/filter higher taxonomy in some way

### ISSUE THREAD

**Issue by deepreef** [dshorthouse/bloodhound#14]
I'm noticing that most of the "not me" records are in groups that I don't work in myself (e.g., insects, birds); so it would be nice to be able to glance down a column of some higher taxonomy information (perhaps just Family, but maybe Order as well) -- or even be able to filter on that parameter as well.

**Comment by dshorthouse** [comment]
That would certainly help matters, it's true. Another way to help this along is some pre-filtering if publications lists were made public in one's ORCID account (see https://github.com/dshorthouse/bloodhound/issues/2). I'm going to keep this ticket open while I wait for the Ebbe Nielsen Challenge dust to settle.

**Comment by dshorthouse** [comment]
Implemented download of csv & then upload claims. Hoping sort/filter/find offline is an appropriate solution. Closing, but please open the ticket anew if it does not suit the use-case.
