### ISSUE TITLE
Add "Not Them" tab to list of claimed specimens obtained by clicking map

### ISSUE THREAD

**Issue by SiobhanLeachman** [dshorthouse/bloodhound#145]
https://bloodhound-tracker.net/Q22113150/specimens?action=collected&country_code=US

I'd like to be able to click the map displaying all the specimens identified or collected by a collect and be taken to a list of specimens that I can then curate. It would make it easier to withdraw attributions that have been mistakenly made.

**Comment by dshorthouse** [comment]
I gather you've found the place where this can be done so will close this one.

**Comment by SiobhanLeachman** [comment]
Thanks David, yes indeed. Sorry about that, I felt like an idiot. Practically as soon as I finished typing I remembered the solution. 

Talk soon

Siobhan
