### ISSUE TITLE
.json response is returned as .html

### ISSUE THREAD

**Issue by mjy** [dshorthouse/bloodhound#18]
When I make a json request, then my browser sees it as html, and it doesn't render it so nicely.

<img width="938" alt="screen shot 2018-09-10 at 9 16 56 am" src="https://user-images.githubusercontent.com/22600/45302980-57943100-b4da-11e8-95b0-7ac1350943ec.png">

**Comment by dshorthouse** [comment]
D'oh! Rookie mistake; forgot to include the appropriate headers. All better now.
