### ISSUE TITLE
accidentally clicked "not mine"

### ISSUE THREAD

**Issue by katherineparys** [dshorthouse/bloodhound#20]
I accidentally clicked "not mine" on a specimen, and now I can't figure out how to get back to it? Any way?

**Comment by dshorthouse** [comment]
Hi @katherineparys. O_o. I wondered when this might happen & I haven't yet come-up with a UI for it. For now, I've made your 16 "not mine" records visible once again. Any ideas how you might want to see records you've declared as "not mine". Another tab & table like all the others?

**Comment by dshorthouse** [comment]
BTW, the ultimate intention of "not mine" is two-fold, both of which still require development:

1. Generally improve search for candidate specimens. There *might* be discoverable patterns in why people select "not mine" that I can use to improve the search capabilities for others. This gets into machine learning space.
2. Don't bother you with similar specimen records when/if I ingest a new swath of GBIF data. You told me "not mine" so I should use it!

**Comment by katherineparys** [comment]
@dshorthouse - I think another table that was out of the way somewhere would work. It was lagging and all of a sudden I had clicked more times! I do like the idea of the not mine for learning purposes. I have a reasonably uncommon name, but there are others that I can see this being far more important for!

**Comment by dshorthouse** [comment]
New tab now present. I may eventually de-emphasize some of these tabs so as not to cause undue confusion...some rarely need to be accessed...but it is what it is for now.
