### ISSUE TITLE
Use schema.org in JSON views

### ISSUE THREAD

**Issue by dshorthouse** [dshorthouse/bloodhound#21]
Requires additions to VIVO. Coordinate with @diatomsRcool.

**Comment by dshorthouse** [comment]
This is much harder than it needs to be. Here's a first crack at this.
```json
{
  "@context": [
    "http://schema.org",
    {
      "identified": "http://rs.tdwg.org/dwc/iri/identifiedBy"
    },
    {
      "recorded": "http://rs.tdwg.org/dwc/iri/recordedBy"
    },
    {
      "Occurrence": "http://rs.tdwg.org/dwc/terms/occurrence"
    }
  ],
  "@type": "Person",
  "@id": "https://orcid.org/0000-0003-1085-6075",
  "@reverse": {
    "identified": [
    ],
    "recorded": [
      {
        "@type": "Occurrence",
        "@id": "https://gbif.org/occurrence/1257921706"
      },
      {
        "@type": "Occurrence",
        "@id": "https://gbif.org/occurrence/1265886824"
      },
      {
        "@type": "Occurrence",
        "@id": "https://gbif.org/occurrence/1847400842"
      },
      {
        "@type": "Occurrence",
        "@id": "https://gbif.org/occurrence/1847400853"
      },
      {
        "@type": "Occurrence",
        "@id": "https://gbif.org/occurrence/1847403656"
      }
    ]
  }
}
```

**Comment by rdmpage** [comment]
Nice use of ```@reverse```! First time I've seen that used. I think ```http://rs.tdwg.org/dwc/terms/occurrence``` should be ```http://rs.tdwg.org/dwc/terms/Occurrence``` (capitals for types). Any reason for the way you've written the ```@context``` the way you have. Why not:

```
	"@context": {
		"@vocab": "http://schema.org/",
		"identified": "http://rs.tdwg.org/dwc/iri/identifiedBy",
		"recorded": "http://rs.tdwg.org/dwc/iri/recordedBy",
		"Occurrence": "http://rs.tdwg.org/dwc/terms/Occurrence"
	},
```

Do you use [JSON-LD Playground](https://json-ld.org/playground/) to check that the syntax is OK and that the triples make sense?

**Comment by dshorthouse** [comment]
Thanks! No particular reason other than what I saw in some JSON-LD docs. Fixed and deployed: https://bloodhound.shorthouse.net/0000-0003-0768-1286/specimens.json

**Comment by dshorthouse** [comment]
The only pitfall to what I've done here is zero attempt at using PROV Activities. But all that seemed so hopelessly heavy, making it extremely difficult to consume in non-JSON-LD contexts.

**Comment by rdmpage** [comment]
> making it extremely difficult to consume in non-JSON-LD contexts.

Not sure what this means. Provenance is a pain, I did briefly explore nanopubs as a way to include provenance. It's cool, but generates LOTS of additional triples, such that you end up saying more about how you got the result than the result itself :(

**Comment by dshorthouse** [comment]
> non-JSON-LD contexts
My poor way of describing the consumer of a JSON web service that had no interest seeing/using in the LD bits of the response but instead merely wants to use the key:value pairs as provided.
