### ISSUE TITLE
There's a typo in the "Deposited At" tab

### ISSUE THREAD

**Issue by rdmpage** [dshorthouse/bloodhound#37]
The left column is labelled "Collected Specimens Deposted At" when it should be "Collected Specimens Depos**i**ted At" (note the "I" in "Deposited").

<img width="1082" alt="screenshot 2019-02-13 11 51 10" src="https://user-images.githubusercontent.com/83306/52709835-bf690f00-2f85-11e9-9205-b08b3bd8e891.png">

**Comment by dshorthouse** [comment]
🥇 D'oh! Thanks for that; all better.
