### ISSUE TITLE
Authenticated Users

### ISSUE THREAD

**Issue by Jegelewicz** [dshorthouse/bloodhound#38]
How do you become an authenticated user? I suggest that a bit more instructive content on the site would help potential users make better use of the tool.

**Comment by dshorthouse** [comment]
Thanks for this. Authentication is through ORCID. I'll add a "How to" page then close this ticket once I roll that out.

**Comment by dshorthouse** [comment]
A start to help guide this a bit. https://bloodhound-tracker.net/get-started
