### ISSUE TITLE
Allow sorting of lists by column headers

### ISSUE THREAD

**Issue by dshorthouse** [dshorthouse/bloodhound#6]
If users could sort (and also filter) columns by clicking headers, this would help accelerate the task of tagging specimen records.

**Comment by listona** [comment]
You are right – looking deeper I see lots of Hymenoptera collected by A.D. Liston.  What about adding a single coarse filter for taxonomy?

**Comment by dshorthouse** [comment]
> Alternatively, what if users could download their records as a CSV, filter and edit offline, and then upload the edited file?

That's an interesting idea, though I wonder what all of us mean by "edited". As you may well know, there are errors in GBIF data, some quite egregious. As much as I'd like to capture whatever edits might be present in a csv upload (eg determination fixed, dates or coordinates repaired, etc.), they would be short-lived. I rebuild Bloodhound every few weeks from a fresh download from GBIF.

The core of Bloodhound is essentially a linking table with three columns of data: gbifID, action, and ORCID. "Action" at the moment consists of up to two, comma-separated verbs: "identified" or "recorded" - because those have DarwinCore equivalents. There is not yet a standard to express anything else, but there's ongoing work on this.

If we're content with what amounts to capturing little else than gbifID & action (I can get ORCID from a user's session) in an offline csv for eventual upload & bulk claim, I can see what it would take to pull this together. To be clearer, I'd offer a csv download of records that can be claimed with a new, empty column called "action". The file would have all the columns I pull from from GBIF + that new "action" column in which you'd declare either "recorded", "identified", or "recorded,identified". Upon upload, I'd only be looking for gbifID & action to construct the linkage, but would ignore all else in the upload.

So, what do you think?

**Comment by listona** [comment]
Thanks for the detailed explanation.  Your solution would accomplish what I had in mind – I am very happy to serve as a beta tester!

**Comment by dshorthouse** [comment]
Implemented download and then upload of csv file.

**Comment by listona** [comment]
Great!  It took me about 45 minutes to annotate 10,000 records. Unfortunately, I was not able to upload as csv or txt. My file is < 5Mbp. I’ve attached the text file here.

**Comment by dshorthouse** [comment]
> Great! It took me about 45 minutes to annotate 10,000 records. Unfortunately, I was not able to upload as csv or txt. My file is < 5Mbp. I’ve attached the text file here.

Sorry about that. Can I get you to send to davidpshorthouse@gmail.com. Receipt through GitHub munged the attachment.

**Comment by dshorthouse** [comment]
Finally sorted it out, @listona & I uploaded your csv. There was a character encoding issue on the server that took some effort to find and solve.

**Comment by listona** [comment]
Great - the results are very nice to see!
Aaron
