### ISSUE TITLE
Create more thorough helping workflow

### ISSUE THREAD

**Issue by dshorthouse** [dshorthouse/bloodhound#65]
The workflow for helping others is currently rudimentary and is in need of more thorough sets of features, especially when helping the deceased. Items to consider:

1. When/how to make profiles for deceased public.
2. How to correct mistakes made in declaring “not them”, which presently disappear from anyone’s view.
3. Should more than one user have a say in a single claim on someone else’s behalf?
4. Should there be a “might be them, but not sure” button + interface to bubble these up for review by others for confirmation?

**Comment by kcopas** [comment]
Thanks for these, David—I was jotting notes along each of these lines during my own testing. 

I found the first one a little surprising/confounding. I've now got some nice numbers for my own efforts (fwiw, but that's not why I was doing it), but it seems to have little to show for of substance if none of the new (deceased) people I added are public (yet?). Be especially glad to see Lucy Cranwell and Lucy Moore surface.

On item #3, I feel pretty certain I clicked one line too high while looking at either Nabokov or Aimé Bonpland that I know of—and there could be cases where I didn't notice my possible error.

Maybe there's something to learn from the simple community consensus rules used in iNaturalist?

**Comment by dshorthouse** [comment]
Kyle - I can see how the first one is confounding, but there are sensitivities at play here that need careful consideration. It's the loved ones they left behind who need to be thought about and respected. Recency since death before we make public must be handled with the appropriate level of care and compassion. I have no idea how to best navigate these issues. Some will welcome an opportunity to remember loved ones in this way but we have to respect their time to grieve. That said, I'll make Lucy Cranwell and Lucy Moore's profiles public while we mull these issues.

Indeed, I was thinking about iNaturalist's community consensus. Before I get too far along in developing this, I'll have to think about where/how this *should* be done and why. Requiring an ORCID account will dissuade most people who would want to be involved in helping others claim their specimens. If we think more broadly about the motivations for claiming others' specimens, we immediately realize that this is a very real, emotional experience. A list of "trainers" as I've cutely called this is nowhere near enough. It needs to be much more special than that.

**Comment by kcopas** [comment]
Cool, thanks for that. 

And who knew there were sensitivities? I'll be sure to make note of it for my GDPR session at SPNHC. And to say with confidence that I now officially **have** been mansplained. ;-P

As a non-specialist, my interest seems to gravitate toward the less-than-recently-dead. I doubt the von Humboldt or Bonpland families will pitch much of a fuss. Could you not set a threshold and presume that subjects are public and scientific figures of note based on a) the presence of Wikidata page and b) a date of death prior to whatever year you feel is suitable timespan for grieving? Basing this on Wikidata fields would also encourage some editing there, which I suspect you'd favour as well...

**Comment by dshorthouse** [comment]
Mansplained? Oh dear. My apologies.

Yes, I could set a date since deceased. These do in fact come from wikidata. I can also imagine a scenario where an arbitrary threshold is *not* desirable such as family members who claim specimens for a recently deceased relative by first creating a wikidata entry. That sounds like an unlikely edge case, but it's already happened! It's partly the reason why I'm sensitive to these nuances & it's also a significant driver to keep pushing on new developments and ways to look at these data.

Do you think #62 is appropriate for the first item in the list?

**Comment by kcopas** [comment]
> 4. Should there be a “might be them, but not sure” button + interface to bubble these up for review by others for confirmation?

+1 on this suggestion—it would be very helpful at times.

**Comment by dshorthouse** [comment]
With the exception of 4 above (new ticket #84), the helping interface has been fleshed out to be similar (and hopefully familiar) to one's profile tabs.
