### ISSUE TITLE
Jean-Baptiste Leschenault de La Tour

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#71]
Curious to know why I can't get match to claim specimens for the above explorer. He's got
pages on both [Wikipedia](https://en.wikipedia.org/wiki/Jean-Baptiste_Leschenault_de_La_Tour) and
[Wikidata](https://www.wikidata.org/wiki/Q1684666). 

Not sure why he'd go missing, but if we can connect him, it looks as if there are [at least a few hundred specimens he collected](https://www.gbif.org/occurrence/search?recorded_by=leschenault&advanced=1) available through GBIF.org.

**Comment by dshorthouse** [comment]
Ooh, that’s an interesting one. In short, the parser chokes at finding a last name. That happens while processing occurrences and while creating people records from wikidata so the issue hits us from both sides. This is a good one to add to the test suite and then see if I can do anything to allow it to push through.

**Comment by dshorthouse** [comment]
All the various representations of his name (and how then subsequently parsed) are...ummm...interesting: https://bloodhound-tracker.net/agents?q=Leschenault

**Comment by kcopas** [comment]
Is the fact that the same thing happens—or doesn't happen—with Heinrich Bürger (assistant and successor to Philipp Franz Von Siebold in Japan) down to the same issue? 

The pieces are all there:
+ [Wikipedia](https://en.wikipedia.org/wiki/Heinrich_B%C3%BCrger) 
+ [Wikidata](https://www.wikidata.org/wiki/Q69386)
+ [GBIF.org](https://www.gbif.org/occurrence/search?recorded_by=b%C3%BCrger%20h&advanced=1)

**Comment by dshorthouse** [comment]
That one’s different. I’ve drawn an arbitrary line in the sand to accept info. from wikidata only when there are birth & death dates accurate to the day + a few properties to search on such as IPNI identifiers & Entomologists of the world. My hope in requiring this degree of precision on dates is to better support DQ queries and inferences in addition to getting better data into wikidata.

**Comment by dshorthouse** [comment]
Closed this one because updated the parser. However, this requires processing all new data from GBIF, which won't be done until end-June.

**Comment by kcopas** [comment]
Not sure if the data's been reprocessed, but I still can't get an effective match for Leschenault de La Tour. There are dozens of specimens under his various cognates, including at least one type that's not marked as such…

**Comment by dshorthouse** [comment]
Sorry, seems my logic in Elasticsearch still requires work. For what it's worth, if you visit https://bloodhound-tracker.net/help-others/Q1684666 while logged in, you'll see (most?) of the specimens that could be attributed to him.

**Comment by kcopas** [comment]
No apologies needed, bruh…

**Comment by dshorthouse** [comment]
Just pushed a tweak to search & now Mr. J. B. L. C. T. L. D. La Tour should be searchable. This will cause more spurious results in users' candidate list of specimens to be claimed (code for search is cross-purpose), but better this than not finding them at all I guess.
