### ISSUE TITLE
Bracket causing suggested ID to fail? 

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#82]
Okay, coming back to what really got me into this craziness. There are about ten specimens from the so-called Perry expedition to Japan that Asa Gray identified, but I think the odd orthography has kept them from turning up—see [two of them here](https://bloodhound-tracker.net/Q65939551/specimens?page=5) (with the rest appearing elsewhere in Morrow's collection).  

All of them read:

`[A. Gray (scripsit) W. T. Kittredge, 2014]`

Is there any way to loosen the search results (without creating chaos) or force these to appear? I've no doubt that Asa Gray's our man here…

**Comment by dshorthouse** [comment]
This is a consequence of the logic in the stand-alone DwcAgent gem used to parse, https://github.com/dshorthouse/dwc_agent. There's a ton of content in recordedBy or identifiedBy with cruft within square brackets either wrapped around all their strings of legible or illegible text or within portions of their content. Most of the examples are the latter, eg "A. Gray [May, 1800]". So, I chose to say (perhaps questionably), "all stuff in brackets is a note-to-self, not a person's name". Even the brackets here in your example here must mean something, right?

That said, I'll  see if I can adjust the logic in the gem and let content through when fully wrapped by square brackets. Interestingly though, when I manually remove the brackets in your example, the parsed result is:

```
DwcAgent.parse "A. Gray (scripsit) W. T. Kittredge, 2014"
=> [#<Name family="Kittredge" given="A. Gray W. T.">]
```
😢

**Comment by dshorthouse** [comment]
Closed here to be dealt with in dwc_agent gem.
