### ISSUE TITLE
Wikidata-enabled names still MIA

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#85]
Not sure how much latency there is with edits to Wikidata, but a couple days after entering improving birth years to birth dates, I'm still waiting to see this pair turn up:
+ [Winona Hazel Welch](https://www.wikidata.org/wiki/Q21340801)
+ [Daniel Cady Eaton](https://www.wikidata.org/wiki/Q5216728)

I know it's quite possible that I'm still falling short of prepping the Wikidata page with some key element.

**Comment by dshorthouse** [comment]
My fault. The SPARQL statement I call was timing out. I split it up into smaller statements & now my cron job can execute without throwing an error. We should be good now. 🤞
