### ISSUE TITLE
Jeanne Baré: MIA

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#91]
Sorry, I’m really not trying to find edge cases. 

I don’t know whether she’s credited with any collecting activity on her voyage in mufti with Bougainville, but Wikidata-enabled botanist [Jeanne Baré](https://www.wikidata.org/wiki/Q437168) still isn’t popping up, in any event.

**Comment by dshorthouse** [comment]
She’s there now. She didn’t have any other identifiers that I fish for so was an unknown. Once I tidy some other code (will take a few days), I’ll make available my UI for adding people using wikidata Q numbers or ORCID identifiers.

**Comment by kcopas** [comment]
No need to reopen this, but a related question: am I right in thinking you're also scanning the 'also known as' entries for suggested matches? I've added a few others here in the event they turn up any other choices (nothing yet—cf. https://www.nybg.org/blogs/science-talk/2014/03/the-amazing-feat-of-jeanne-baret)

**Comment by dshorthouse** [comment]
Ah, that’s another little UI element that I haven’t yet made available. I just refreshed her wikidata content.
