### ISSUE TITLE
Joan Isern Batlló i Carrera

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#92]
I'm okay waiting until you make a UI available to add him, but in the meantime, Spanish botanist [Joan Isern Batlló i Carrera](https://www.wikidata.org/wiki/Q5950070) seems to be missing.

**Comment by dshorthouse** [comment]
He too does not have identifiers like IPNI or Harvard Index of Botanists so was dark to the SPARQL query I have. Added him just now because it’s really quick.
