### ISSUE TITLE
Possible J.E. Wikström identifier claims not discovered

### ISSUE THREAD

**Issue by kcopas** [dshorthouse/bloodhound#98]
There's a small set of specimens in The Bergius Herbarium collected by Anders Sparrman that list 'J.E. Wikström' as the identifier e.g. https://www.gbif.org/occurrence/1211093508

However, none of these are being discovered as possible claims—and Sparrman's network looks so lonely!

Lots of other Wikströms other than our man show up in the fuzzy match, but these records don't. Is it simply because 'J.E. Wikström' doesn't appear as an alias in Wikidata? But why wouldn't just 'Wikström' work? I've added the J.E. variant there, in the event it helps.

**Comment by dshorthouse** [comment]
I eliminated parsing as part of search some time ago and while it helps deal with unusual issues like reversal of name parts with no punctuation, it tends to miss the basics. I refreshed the alias info from wikidata and you’ll see a boat load of more candidate records. So, takehome is yes, initials in alias help (but not always so).
